apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nodeangular 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeangular 
    spec:
      containers:
        - name: nodeangular 
          image: aksangular.azurecr.io/nodeangular
          ports:
          - containerPort: 8081